### ISSUE TITLE
PySide2/charts/callout.py L131. Function mapToParent does not exist.

### ISSUE THREAD

**Issue by McMozart4562** [PyQt5/Examples#1]
A function is called here that does not exist. The example will freeze.

**Comment by McMozart4562** [comment]
Missing self qualifier.

**Comment by 892768447** [comment]
Which version do you use?
I test it on PySide5.15.0 and It's ok.

**Comment by McMozart4562** [comment]
It was just a missing self reference. Ill grab my build info a bit later.
